; 이 파일의 호스트 목록은 대시보드 등록/삭제 시 자동 생성됩니다.
[all]
instructor_db ansible_host=100.120.178.40 ansible_user=instructor_db
lecturedb ansible_host=100.112.225.33 ansible_user=lecturedb
webs ansible_host=100.122.19.67 ansible_user=webs
