---
kisa_local_root: "{{ playbook_dir }}/.."
kisa_local_check_dir: "{{ kisa_local_root }}/check"
kisa_local_fix_dir: "{{ kisa_local_root }}/fix"
kisa_local_lib_dir: "{{ kisa_local_root }}/lib"

kisa_remote_dir: /opt/kisa_v2

kisa_remote_active_dir: "{{ kisa_remote_dir }}/current"

kisa_check_item_timeout: 120

kisa_connectivity_risk_codes:
  - U-01
